// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYuPL91WPk6Z7QyBhhubMfncNLGt8FDk',
    appId: '1:937332773772:web:b9749984cc43290b26bca9',
    messagingSenderId: '937332773772',
    projectId: 'moviex-efaed',
    authDomain: 'moviex-efaed.firebaseapp.com',
    storageBucket: 'moviex-efaed.firebasestorage.app',
    measurementId: 'G-SBQPPQWNNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBubDPJWyGoPMHHZkMNkRg6pvPsmHUEx1U',
    appId: '1:937332773772:android:8b4fdd6b7028866a26bca9',
    messagingSenderId: '937332773772',
    projectId: 'moviex-efaed',
    storageBucket: 'moviex-efaed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-S-z0qbzR6VbZbVVlRXCc2YBVv_DA048',
    appId: '1:937332773772:ios:fcd1bf9e142df74026bca9',
    messagingSenderId: '937332773772',
    projectId: 'moviex-efaed',
    storageBucket: 'moviex-efaed.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-S-z0qbzR6VbZbVVlRXCc2YBVv_DA048',
    appId: '1:937332773772:ios:fcd1bf9e142df74026bca9',
    messagingSenderId: '937332773772',
    projectId: 'moviex-efaed',
    storageBucket: 'moviex-efaed.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPYuPL91WPk6Z7QyBhhubMfncNLGt8FDk',
    appId: '1:937332773772:web:266862958c2a76d526bca9',
    messagingSenderId: '937332773772',
    projectId: 'moviex-efaed',
    authDomain: 'moviex-efaed.firebaseapp.com',
    storageBucket: 'moviex-efaed.firebasestorage.app',
    measurementId: 'G-YB9LW0K45E',
  );
}
